[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "ai-interview-voice-agent"
version = "1.0.0"
description = "AI-powered voice interview agent built with LiveKit Agents"
requires-python = ">=3.10, <3.15"

dependencies = [
    "fastapi",
    "groq",
    "livekit-agents>=1.6.1",
    "livekit-plugins-deepgram",
    "pymongo",
    "python-dotenv",
    "pydantic",
    "uvicorn",
]


[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "ruff",
]


[tool.uv]
constraint-dependencies = [
    "yarl<1.24"
]


[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-dir]
"" = "src"


[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"


[tool.ruff]
line-length = 88
target-version = "py312"


[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "B",
    "A",
    "C4",
    "UP",
    "SIM",
    "RUF"
]

ignore = [
    "E501"
]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
